export type AuthorityDiscoveryType = 'rss' | 'sitemap' | 'api' | 'index_page' | 'pdf_index';

export interface AuthoritySourceConfig {
  id: string;
  org: string;
  baseUrl: string;
  allowedDomains: string[];
  discoveryType: AuthorityDiscoveryType;
  entryUrls: string[];
  region: 'US' | 'UK' | 'CN' | 'GLOBAL';
  language: 'zh' | 'en';
  locale: string;
  audience: string[];
  topics: string[];
  enabled: boolean;
  fetchIntervalMinutes: number;
  maxPagesPerRun: number;
  maxDiscoveryIndexPages?: number;
  parserId: string;
}

export const AUTHORITY_SOURCES: AuthoritySourceConfig[] = [
  {
    id: 'who',
    org: 'WHO',
    baseUrl: 'https://www.who.int',
    allowedDomains: ['who.int'],
    discoveryType: 'sitemap',
    entryUrls: [
      'https://www.who.int/sitemaps/sitemapindex.xml',
    ],
    region: 'GLOBAL',
    language: 'en',
    locale: 'en',
    audience: ['孕妇', '新生儿家长', '婴幼儿家长'],
    topics: ['pregnancy', 'newborn', 'feeding', 'vaccination', 'common-symptoms'],
    enabled: true,
    fetchIntervalMinutes: 360,
    maxPagesPerRun: 300,
    parserId: 'who',
  },
  {
    id: 'cdc',
    org: 'CDC',
    baseUrl: 'https://www.cdc.gov',
    allowedDomains: ['cdc.gov'],
    discoveryType: 'sitemap',
    entryUrls: [
      'https://www.cdc.gov/wcms-auto-sitemap-index.xml',
    ],
    region: 'US',
    language: 'en',
    locale: 'en-US',
    audience: ['孕妇', '新生儿家长', '婴幼儿家长'],
    topics: ['pregnancy', 'newborn', 'feeding', 'vaccination', 'common-symptoms'],
    enabled: true,
    fetchIntervalMinutes: 360,
    maxPagesPerRun: 300,
    parserId: 'cdc',
  },
  {
    id: 'aap',
    org: 'AAP',
    baseUrl: 'https://www.healthychildren.org',
    allowedDomains: ['healthychildren.org'],
    discoveryType: 'sitemap',
    entryUrls: [
      'https://www.healthychildren.org/sitemap.xml',
    ],
    region: 'US',
    language: 'en',
    locale: 'en-US',
    audience: ['新生儿家长', '婴幼儿家长', '母婴家庭'],
    topics: ['newborn', 'feeding', 'vaccination', 'common-symptoms', 'development'],
    enabled: true,
    fetchIntervalMinutes: 360,
    maxPagesPerRun: 300,
    parserId: 'aap',
  },
  {
    id: 'acog',
    org: 'ACOG',
    baseUrl: 'https://www.acog.org',
    allowedDomains: ['acog.org'],
    discoveryType: 'sitemap',
    entryUrls: [
      'https://www.acog.org/sitemap.xml',
    ],
    region: 'US',
    language: 'en',
    locale: 'en-US',
    audience: ['孕妇', '产后妈妈', '备孕女性'],
    topics: ['pregnancy', 'postpartum', 'feeding', 'common-symptoms'],
    enabled: true,
    fetchIntervalMinutes: 360,
    maxPagesPerRun: 300,
    parserId: 'acog',
  },
  {
    id: 'nhs',
    org: 'NHS',
    baseUrl: 'https://www.nhs.uk',
    allowedDomains: ['nhs.uk'],
    discoveryType: 'sitemap',
    entryUrls: [
      'https://www.nhs.uk/sitemap.xml',
    ],
    region: 'UK',
    language: 'en',
    locale: 'en-GB',
    audience: ['孕妇', '新生儿家长', '婴幼儿家长'],
    topics: ['pregnancy', 'newborn', 'feeding', 'vaccination', 'common-symptoms'],
    enabled: true,
    fetchIntervalMinutes: 360,
    maxPagesPerRun: 300,
    parserId: 'nhs',
  },
  {
    id: 'mayo-clinic-zh',
    org: 'Mayo Clinic',
    baseUrl: 'https://www.mayoclinic.org',
    allowedDomains: ['mayoclinic.org'],
    discoveryType: 'sitemap',
    entryUrls: [
      'https://www.mayoclinic.org/chinese_patient_consumer_web.xml',
    ],
    region: 'US',
    language: 'zh',
    locale: 'zh-CN',
    audience: ['孕妇', '新生儿家长', '婴幼儿家长', '母婴家庭'],
    topics: ['pregnancy', 'newborn', 'feeding', 'vaccination', 'common-symptoms', 'development'],
    enabled: true,
    fetchIntervalMinutes: 720,
    maxPagesPerRun: 180,
    parserId: 'mayo',
  },
  {
    id: 'msd-manuals-cn',
    org: 'MSD Manuals',
    baseUrl: 'https://www.msdmanuals.cn',
    allowedDomains: ['msdmanuals.cn', 'www.msdmanuals.cn'],
    discoveryType: 'sitemap',
    entryUrls: [
      'https://www.msdmanuals.cn/sitemap-index.xml',
    ],
    region: 'GLOBAL',
    language: 'zh',
    locale: 'zh-CN',
    audience: ['孕妇', '新生儿家长', '婴幼儿家长', '母婴家庭'],
    topics: ['pregnancy', 'newborn', 'feeding', 'vaccination', 'common-symptoms'],
    enabled: true,
    fetchIntervalMinutes: 720,
    maxPagesPerRun: 180,
    parserId: 'msd-manuals',
  },
  {
    id: 'nhc-fys',
    org: '国家卫生健康委员会妇幼健康司',
    baseUrl: 'https://www.nhc.gov.cn',
    allowedDomains: ['nhc.gov.cn'],
    discoveryType: 'index_page',
    entryUrls: [
      'https://www.nhc.gov.cn/fys/new_index.shtml',
      'https://www.nhc.gov.cn/fys/c100077/new_list.shtml',
      'https://www.nhc.gov.cn/fys/c100078/new_list.shtml',
      'https://www.nhc.gov.cn/fys/pztq/new_list.shtml',
      'https://www.nhc.gov.cn/fys/mrwy/mrwy_index.shtml',
      'https://www.nhc.gov.cn/fys/mrgzdt/mrwy_list.shtml',
      'https://www.nhc.gov.cn/fys/mrkpxc/mrwy_list.shtml',
      'https://www.nhc.gov.cn/jnr/kajrjjr/dzhxpr_lmtt.shtml',
      'https://www.nhc.gov.cn/jnr/jrjjk/csqxr_lmtt.shtml',
      'https://www.nhc.gov.cn/wjw/wzdt/wzdt.shtml',
    ],
    region: 'CN',
    language: 'zh',
    locale: 'zh-CN',
    audience: ['孕妇', '产后妈妈', '新生儿家长', '婴幼儿家长'],
    topics: ['pregnancy', 'newborn', 'feeding', 'development', 'policy'],
    enabled: true,
    fetchIntervalMinutes: 360,
    maxPagesPerRun: 120,
    parserId: 'cn-health',
  },
  {
    id: 'nhc-rkjt',
    org: '国家卫生健康委员会人口监测与家庭发展司',
    baseUrl: 'https://www.nhc.gov.cn',
    allowedDomains: ['nhc.gov.cn'],
    discoveryType: 'index_page',
    entryUrls: [
      'https://www.nhc.gov.cn/rkjcyjtfzs/new_index.shtml',
      'https://www.nhc.gov.cn/rkjcyjtfzs/c100147/new_list.shtml',
      'https://www.nhc.gov.cn/rkjcyjtfzs/c100148/new_list.shtml',
      'https://www.nhc.gov.cn/rkjcyjtfzs/s9993/new_list.shtml',
    ],
    region: 'CN',
    language: 'zh',
    locale: 'zh-CN',
    audience: ['备孕家庭', '孕妇', '新生儿家长', '婴幼儿家长'],
    topics: ['development', 'newborn', 'policy', 'feeding'],
    enabled: true,
    fetchIntervalMinutes: 360,
    maxPagesPerRun: 100,
    parserId: 'cn-health',
  },
  {
    id: 'chinacdc-immunization',
    org: '中国疾病预防控制中心',
    baseUrl: 'https://www.chinacdc.cn',
    allowedDomains: ['chinacdc.cn'],
    discoveryType: 'index_page',
    entryUrls: [
      'https://www.chinacdc.cn/jkkp/mygh/ztrxc/',
      'https://www.chinacdc.cn/jkkp/mygh/ymyf/',
      'https://www.chinacdc.cn/jkyj/mygh02/jswj_mygh/myfw_mygh/',
    ],
    region: 'CN',
    language: 'zh',
    locale: 'zh-CN',
    audience: ['新生儿家长', '婴幼儿家长', '母婴家庭'],
    topics: ['vaccination', 'newborn', 'feeding', 'common-symptoms', 'policy'],
    enabled: true,
    fetchIntervalMinutes: 360,
    maxPagesPerRun: 120,
    parserId: 'cn-health',
  },
  {
    id: 'chinacdc-nutrition',
    org: '中国疾病预防控制中心营养与健康所',
    baseUrl: 'https://www.chinacdc.cn',
    allowedDomains: ['chinacdc.cn'],
    discoveryType: 'index_page',
    entryUrls: [
      'https://www.chinacdc.cn/jkkp/yyjk/rqyy/',
      'https://www.chinacdc.cn/jkkp/yyjk/jbyy/',
    ],
    region: 'CN',
    language: 'zh',
    locale: 'zh-CN',
    audience: ['孕妇', '新生儿家长', '婴幼儿家长', '母婴家庭'],
    topics: ['feeding', 'development', 'newborn', 'common-symptoms'],
    enabled: true,
    fetchIntervalMinutes: 360,
    maxPagesPerRun: 120,
    parserId: 'cn-health',
  },
  {
    id: 'govcn-muying',
    org: '中国政府网',
    baseUrl: 'https://www.gov.cn',
    allowedDomains: ['gov.cn'],
    discoveryType: 'api',
    entryUrls: [
      'https://www.gov.cn/zhengce/zuixin/ZUIXINZHENGCE.json',
    ],
    region: 'CN',
    language: 'zh',
    locale: 'zh-CN',
    audience: ['备孕家庭', '孕妇', '新生儿家长', '婴幼儿家长'],
    topics: ['pregnancy', 'newborn', 'feeding', 'development', 'policy'],
    enabled: true,
    fetchIntervalMinutes: 360,
    maxPagesPerRun: 100,
    parserId: 'cn-health',
  },
  {
    id: 'govcn-jiedu-muying',
    org: '中国政府网政策解读',
    baseUrl: 'https://www.gov.cn',
    allowedDomains: ['gov.cn'],
    discoveryType: 'api',
    entryUrls: [
      'https://www.gov.cn/zhengce/jiedu/ZCJD_QZ.json',
    ],
    region: 'CN',
    language: 'zh',
    locale: 'zh-CN',
    audience: ['备孕家庭', '孕妇', '新生儿家长', '婴幼儿家长'],
    topics: ['pregnancy', 'newborn', 'feeding', 'development', 'policy'],
    enabled: true,
    fetchIntervalMinutes: 360,
    maxPagesPerRun: 120,
    parserId: 'cn-health',
  },
  {
    id: 'ndcpa-immunization',
    org: '国家疾病预防控制局',
    baseUrl: 'https://www.ndcpa.gov.cn',
    allowedDomains: ['ndcpa.gov.cn'],
    discoveryType: 'index_page',
    entryUrls: [
      'https://www.ndcpa.gov.cn/jbkzzx/c100012/common/list.html',
      'https://www.ndcpa.gov.cn/jbkzzx/c100014/common/list.html',
    ],
    region: 'CN',
    language: 'zh',
    locale: 'zh-CN',
    audience: ['孕妇', '新生儿家长', '婴幼儿家长', '母婴家庭'],
    topics: ['vaccination', 'policy', 'newborn', 'common-symptoms'],
    enabled: true,
    fetchIntervalMinutes: 360,
    maxPagesPerRun: 120,
    parserId: 'cn-health',
  },
  {
    id: 'ndcpa-public-health',
    org: '国家疾病预防控制局',
    baseUrl: 'https://www.ndcpa.gov.cn',
    allowedDomains: ['ndcpa.gov.cn'],
    discoveryType: 'index_page',
    entryUrls: [
      'https://www.ndcpa.gov.cn/jbkzzx/c100013/common/list.html',
      'https://www.ndcpa.gov.cn/jbkzzx/c100016/second/list.html',
    ],
    region: 'CN',
    language: 'zh',
    locale: 'zh-CN',
    audience: ['孕妇', '新生儿家长', '婴幼儿家长', '母婴家庭'],
    topics: ['policy', 'common-symptoms', 'vaccination', 'newborn'],
    enabled: true,
    fetchIntervalMinutes: 360,
    maxPagesPerRun: 120,
    parserId: 'cn-health',
  },
  {
    id: 'ncwch-maternal-child-health',
    org: '国家卫生健康委妇幼健康中心',
    baseUrl: 'https://www.ncwchnhc.org.cn',
    allowedDomains: ['ncwchnhc.org.cn', 'www.ncwchnhc.org.cn'],
    discoveryType: 'index_page',
    entryUrls: [
      'https://www.ncwchnhc.org.cn/',
      'https://www.ncwchnhc.org.cn/content/content.html?id=7313481602116358144',
      'https://www.ncwchnhc.org.cn/content/content.html?id=7310547309815664640',
      'https://www.ncwchnhc.org.cn/content/content.html?id=7312390045250359296',
    ],
    region: 'CN',
    language: 'zh',
    locale: 'zh-CN',
    audience: ['备孕家庭', '孕妇', '产后妈妈', '新生儿家长', '婴幼儿家长'],
    topics: ['pregnancy', 'postpartum', 'newborn', 'feeding', 'development', 'common-symptoms'],
    enabled: true,
    fetchIntervalMinutes: 360,
    maxPagesPerRun: 6,
    maxDiscoveryIndexPages: 1,
    parserId: 'cn-health',
  },
  {
    id: 'mchscn-monitoring',
    org: '全国妇幼卫生监测办公室/中国出生缺陷监测中心',
    baseUrl: 'https://www.mchscn.cn',
    allowedDomains: ['mchscn.cn', 'www.mchscn.cn'],
    discoveryType: 'index_page',
    entryUrls: [
      'https://www.mchscn.cn/MaternalSafetyMonitoring-26.html',
      'https://www.mchscn.cn/BirthDefectMonitoring-25.html',
      'https://www.mchscn.cn/ChildHealthMonitoring-27.html',
      'https://www.mchscn.cn/BirthDefectsPrevention-28.html',
    ],
    region: 'CN',
    language: 'zh',
    locale: 'zh-CN',
    audience: ['备孕家庭', '孕妇', '新生儿家长', '婴幼儿家长'],
    topics: ['pregnancy', 'newborn', 'development', 'common-symptoms', 'policy'],
    enabled: true,
    fetchIntervalMinutes: 720,
    maxPagesPerRun: 6,
    maxDiscoveryIndexPages: 1,
    parserId: 'cn-health',
  },
  {
    id: 'cnsoc-dietary-guidelines',
    org: '中国营养学会/中国居民膳食指南',
    baseUrl: 'http://dg.cnsoc.org',
    allowedDomains: ['dg.cnsoc.org', 'cnsoc.org'],
    discoveryType: 'index_page',
    entryUrls: [
      'http://dg.cnsoc.org/',
      'http://dg.cnsoc.org/article/04/gc5cUak3RhSGheqSaRljnA.html',
      'http://dg.cnsoc.org/article/04/hjgfxca3Ra69sKbvqDETbg.html',
      'http://dg.cnsoc.org/article/04/Qokq-WkDRZW3nhyFH0qF5A.html',
    ],
    region: 'CN',
    language: 'zh',
    locale: 'zh-CN',
    audience: ['备孕家庭', '孕妇', '产后妈妈', '新生儿家长', '婴幼儿家长'],
    topics: ['feeding', 'pregnancy', 'postpartum', 'newborn', 'development'],
    enabled: true,
    fetchIntervalMinutes: 720,
    maxPagesPerRun: 6,
    maxDiscoveryIndexPages: 1,
    parserId: 'cn-health',
  },
  {
    id: 'chinanutri-maternal-child',
    org: '中国疾病预防控制中心营养与健康所',
    baseUrl: 'https://www.chinanutri.cn',
    allowedDomains: ['chinanutri.cn', 'www.chinanutri.cn'],
    discoveryType: 'index_page',
    entryUrls: [
      'https://www.chinanutri.cn/',
      'https://www.chinanutri.cn/yyjkzxpt/yyjkkpzx/',
      'https://www.chinanutri.cn/yyjkzxpt/yyjkkpzx/xcclk/',
      'https://www.chinanutri.cn/xwzx_238/xyxw/201605/t20160526_130084.html',
    ],
    region: 'CN',
    language: 'zh',
    locale: 'zh-CN',
    audience: ['备孕家庭', '孕妇', '产后妈妈', '新生儿家长', '婴幼儿家长'],
    topics: ['feeding', 'pregnancy', 'postpartum', 'newborn', 'development'],
    enabled: true,
    fetchIntervalMinutes: 720,
    maxPagesPerRun: 6,
    maxDiscoveryIndexPages: 1,
    parserId: 'cn-health',
  },
  {
    id: 'cma-kepu-maternal-child',
    org: '中华医学会',
    baseUrl: 'https://www.cma.org.cn',
    allowedDomains: ['cma.org.cn', 'www.cma.org.cn'],
    discoveryType: 'index_page',
    entryUrls: [
      'https://www.cma.org.cn/col/col4584/index.html',
    ],
    region: 'CN',
    language: 'zh',
    locale: 'zh-CN',
    audience: ['备孕家庭', '孕妇', '产后妈妈', '新生儿家长', '婴幼儿家长'],
    topics: ['pregnancy', 'postpartum', 'newborn', 'feeding', 'common-symptoms', 'development'],
    enabled: true,
    fetchIntervalMinutes: 1440,
    maxPagesPerRun: 80,
    maxDiscoveryIndexPages: 3,
    parserId: 'cma-kepu',
  },
  // Third-party medical content platform. Disabled by default because the
  // site's robots policy explicitly forbids large-language-model crawlers.
  {
    id: 'dxy-maternal',
    org: '丁香医生',
    baseUrl: 'https://dxy.com',
    allowedDomains: ['dxy.com', 'm.dxy.com'],
    discoveryType: 'index_page',
    entryUrls: [
      'https://m.dxy.com/articles/24826',
      'https://dxy.com/',
      'https://dxy.com/articles/recommend/doctors',
    ],
    region: 'CN',
    language: 'zh',
    locale: 'zh-CN',
    audience: ['备孕家庭', '孕妇', '新生儿家长', '婴幼儿家长'],
    topics: ['pregnancy', 'newborn', 'feeding', 'common-symptoms'],
    enabled: false,
    fetchIntervalMinutes: 720,
    maxPagesPerRun: 60,
    maxDiscoveryIndexPages: 3,
    parserId: 'dxy',
  },
  // Third-party medical content platform discovered from mother-and-baby
  // category pages, separated from official authority sources. Disabled from
  // automatic runs because live diagnosis mostly returns collections/case
  // narratives that fail the quality gate.
  {
    id: 'chunyu-maternal',
    org: '春雨医生',
    baseUrl: 'https://m.chunyuyisheng.com',
    allowedDomains: ['m.chunyuyisheng.com', 'www.chunyuyisheng.com', 'chunyuyisheng.com'],
    discoveryType: 'index_page',
    entryUrls: [
      'https://m.chunyuyisheng.com/m/health_news_home/?channel_id=6',
    ],
    region: 'CN',
    language: 'zh',
    locale: 'zh-CN',
    audience: ['备孕家庭', '孕妇', '新生儿家长', '婴幼儿家长'],
    topics: ['pregnancy', 'newborn', 'feeding', 'common-symptoms'],
    enabled: false,
    fetchIntervalMinutes: 720,
    maxPagesPerRun: 100,
    maxDiscoveryIndexPages: 10,
    parserId: 'chunyu',
  },
  {
    id: 'youlai-pregnancy-guide',
    org: '有来医生',
    baseUrl: 'https://m.youlai.cn',
    allowedDomains: ['m.youlai.cn', 'youlai.cn'],
    discoveryType: 'index_page',
    entryUrls: [
      'https://m.youlai.cn/special/advisor/vezz0BpCQ3.html',
    ],
    region: 'CN',
    language: 'zh',
    locale: 'zh-CN',
    audience: ['备孕家庭', '孕妇'],
    topics: ['pregnancy', 'feeding', 'development'],
    enabled: true,
    fetchIntervalMinutes: 1440,
    maxPagesPerRun: 60,
    maxDiscoveryIndexPages: 60,
    parserId: 'youlai',
  },
  {
    id: 'dayi-maternal-child',
    org: '中国医药信息查询平台',
    baseUrl: 'https://www.dayi.org.cn',
    allowedDomains: ['dayi.org.cn', 'www.dayi.org.cn'],
    discoveryType: 'index_page',
    entryUrls: [
      'https://www.dayi.org.cn/search?keyword=%E5%AD%95%E5%A6%87',
      'https://www.dayi.org.cn/search?keyword=%E5%AD%95%E6%9C%9F',
      'https://www.dayi.org.cn/search?keyword=%E4%BA%A7%E5%90%8E',
      'https://www.dayi.org.cn/search?keyword=%E6%96%B0%E7%94%9F%E5%84%BF',
      'https://www.dayi.org.cn/search?keyword=%E5%A9%B4%E5%84%BF',
      'https://www.dayi.org.cn/search?keyword=%E6%AF%8D%E4%B9%B3',
    ],
    region: 'CN',
    language: 'zh',
    locale: 'zh-CN',
    audience: ['备孕家庭', '孕妇', '产后妈妈', '新生儿家长', '婴幼儿家长'],
    topics: ['pregnancy', 'postpartum', 'newborn', 'feeding', 'common-symptoms', 'development'],
    enabled: true,
    fetchIntervalMinutes: 1440,
    maxPagesPerRun: 80,
    maxDiscoveryIndexPages: 6,
    parserId: 'dayi',
  },
  {
    id: 'kepuchina-maternal-child',
    org: '科普中国',
    baseUrl: 'https://www.kepuchina.cn',
    allowedDomains: ['kepuchina.cn', 'www.kepuchina.cn'],
    discoveryType: 'index_page',
    entryUrls: [
      'https://www.kepuchina.cn/search/index?search=%E6%AF%8D%E4%B9%B3%E5%96%82%E5%85%BB&search_type=1&sort=0',
      'https://www.kepuchina.cn/search/index?search=%E6%96%B0%E7%94%9F%E5%84%BF%E6%8A%A4%E7%90%86&search_type=1&sort=0',
      'https://www.kepuchina.cn/search/index?search=%E6%96%B0%E7%94%9F%E5%84%BF%E9%BB%84%E7%96%B8&search_type=1&sort=0',
      'https://www.kepuchina.cn/search/index?search=%E5%AE%9D%E5%AE%9D%E8%85%B9%E6%B3%BB&search_type=1&sort=0',
      'https://www.kepuchina.cn/search/index?search=%E5%A9%B4%E5%84%BF%E8%BE%85%E9%A3%9F&search_type=1&sort=0',
      'https://www.kepuchina.cn/search/index?search=%E5%AD%95%E5%A6%87%E8%90%A5%E5%85%BB&search_type=1&sort=0',
      'https://www.kepuchina.cn/search/index?search=%E5%88%86%E5%A8%A9%E9%95%87%E7%97%9B&search_type=1&sort=0',
      'https://www.kepuchina.cn/search/index?search=%E5%A9%B4%E5%B9%BC%E5%84%BF%E5%96%82%E5%85%BB&search_type=1&sort=0',
    ],
    region: 'CN',
    language: 'zh',
    locale: 'zh-CN',
    audience: ['备孕家庭', '孕妇', '产后妈妈', '新生儿家长', '婴幼儿家长'],
    topics: ['pregnancy', 'postpartum', 'newborn', 'feeding', 'common-symptoms', 'development'],
    enabled: true,
    fetchIntervalMinutes: 1440,
    maxPagesPerRun: 96,
    maxDiscoveryIndexPages: 8,
    parserId: 'kepuchina',
  },
  {
    id: 'haodf-maternal-child',
    org: '好大夫在线',
    baseUrl: 'https://www.haodf.com',
    allowedDomains: ['haodf.com', 'www.haodf.com', 'm.haodf.com'],
    discoveryType: 'index_page',
    entryUrls: [
      'https://www.haodf.com/neirong/wenzhang/9394363019.html',
      'https://www.haodf.com/neirong/wenzhang/9394540068.html',
      'https://www.haodf.com/neirong/wenzhang/9394471422.html',
      'https://www.haodf.com/neirong/wenzhang/9065760337.html',
    ],
    region: 'CN',
    language: 'zh',
    locale: 'zh-CN',
    audience: ['孕妇', '产后妈妈', '新生儿家长', '婴幼儿家长'],
    topics: ['pregnancy', 'postpartum', 'newborn', 'feeding', 'common-symptoms', 'development'],
    enabled: true,
    fetchIntervalMinutes: 1440,
    maxPagesPerRun: 24,
    maxDiscoveryIndexPages: 4,
    parserId: 'haodf',
  },
  // Disabled from automatic runs: live diagnosis shows mostly stale,
  // editor-style content with weak professional signals. Keep the parser and
  // tests so manually vetted URLs can still be evaluated by the quality gate.
  {
    id: 'familydoctor-maternal',
    org: '家庭医生在线',
    baseUrl: 'https://www.familydoctor.com.cn',
    allowedDomains: ['familydoctor.com.cn', 'www.familydoctor.com.cn', 'm.familydoctor.com.cn'],
    discoveryType: 'index_page',
    entryUrls: [
      'https://www.familydoctor.com.cn/yc/',
      'https://www.familydoctor.com.cn/baby/baby/jbhl/',
    ],
    region: 'CN',
    language: 'zh',
    locale: 'zh-CN',
    audience: ['备孕家庭', '孕妇', '新生儿家长', '婴幼儿家长'],
    topics: ['pregnancy', 'newborn', 'feeding', 'common-symptoms', 'development'],
    enabled: false,
    fetchIntervalMinutes: 1440,
    maxPagesPerRun: 120,
    maxDiscoveryIndexPages: 8,
    parserId: 'familydoctor',
  },
  // Disabled from automatic runs: category pages are dominated by social-style
  // articles and case news, which are too noisy for an automatic knowledge feed.
  {
    id: 'yilianmeiti-maternal-child',
    org: '医联媒体',
    baseUrl: 'https://www.yilianmeiti.com',
    allowedDomains: ['yilianmeiti.com', 'www.yilianmeiti.com', 'm.yilianmeiti.com'],
    discoveryType: 'index_page',
    entryUrls: [
      'https://www.yilianmeiti.com/3/',
      'https://www.yilianmeiti.com/6/',
      'https://www.yilianmeiti.com/43/',
      'https://www.yilianmeiti.com/45/',
      'https://www.yilianmeiti.com/16/',
    ],
    region: 'CN',
    language: 'zh',
    locale: 'zh-CN',
    audience: ['备孕家庭', '孕妇', '产后妈妈', '新生儿家长', '婴幼儿家长'],
    topics: ['pregnancy', 'postpartum', 'newborn', 'feeding', 'common-symptoms', 'development'],
    enabled: false,
    fetchIntervalMinutes: 1440,
    maxPagesPerRun: 48,
    maxDiscoveryIndexPages: 4,
    parserId: 'yilianmeiti',
  },
];

export const OFFICIAL_AUTHORITY_SOURCE_IDS = new Set([
  'who',
  'cdc',
  'aap',
  'acog',
  'nhs',
  'mayo-clinic-zh',
  'msd-manuals-cn',
  'nhc-fys',
  'nhc-rkjt',
  'chinacdc-immunization',
  'chinacdc-nutrition',
  'govcn-muying',
  'govcn-jiedu-muying',
  'ndcpa-immunization',
  'ndcpa-public-health',
  'ncwch-maternal-child-health',
  'mchscn-monitoring',
  'cnsoc-dietary-guidelines',
  'chinanutri-maternal-child',
  'cma-kepu-maternal-child',
]);

export function getAuthoritySourceConfig(sourceId: string): AuthoritySourceConfig | undefined {
  return AUTHORITY_SOURCES.find((source) => source.id === sourceId);
}

export function listEnabledAuthoritySources(): AuthoritySourceConfig[] {
  return AUTHORITY_SOURCES.filter((source) => source.enabled);
}

export function listEnabledOfficialAuthoritySources(): AuthoritySourceConfig[] {
  return AUTHORITY_SOURCES.filter((source) => source.enabled && OFFICIAL_AUTHORITY_SOURCE_IDS.has(source.id));
}

export function inferAuthorityLocaleDefaults(
  sourceId?: string,
  region?: string,
): { sourceLanguage: 'zh' | 'en'; sourceLocale: string } {
  const matched = sourceId ? getAuthoritySourceConfig(sourceId) : undefined;
  if (matched) {
    return {
      sourceLanguage: matched.language,
      sourceLocale: matched.locale,
    };
  }

  if (region === 'CN') {
    return { sourceLanguage: 'zh', sourceLocale: 'zh-CN' };
  }

  if (region === 'UK') {
    return { sourceLanguage: 'en', sourceLocale: 'en-GB' };
  }

  if (region === 'US') {
    return { sourceLanguage: 'en', sourceLocale: 'en-US' };
  }

  return { sourceLanguage: 'en', sourceLocale: 'en' };
}
